<a href="https://colab.research.google.com/github/Carolinsrainbow/UC_AnalisisdeDatosEnPython/blob/main/Ev4_Resuelta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instrucciones

Descargar el archivo de Excel llamado “Datos.xls” ubicado en la sección de "Bienvenida" del curso.
Leer atentamente las preguntas.
Realizar cálculos, desarrollos y análisis en base al archivo.
Las respuestas que debes seleccionar están asociadas a los códigos o resultados que obtendrás del trabajo con el archivo.

In [ ]:
# Incorporamos los paquetes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.transforms as transforms
import seaborn as sns

In [ ]:
# Incorporamos las pestañas de excel como datos

#Creamos GRD
GRD_sheet = pd.read_excel('Datos.xls',sheet_name='GRD')

#Creamos Hospitales
Hosp_sheet = pd.read_excel('Datos.xls',sheet_name='Hospitales')

#Creamos Informaciones
Info_sheet = pd.read_excel('Datos.xls',sheet_name='Información Histórica')

In [ ]:
#Arreglamos los campos
Hosp_sheet['Nombre Servicio de Salud'] = Hosp_sheet['Nombre Servicio de Salud'].str.strip()

Pregunta 1:
¿Cuál de las siguientes alternativas corresponde a la estimación de la cantidad de pacientes con GRD9 que llegarán el día 425 al Hospital Salvador utilizando un método de media móvil sobre los últimos 5 días (días 420 a 424) redondeado al entero superior?  

In [ ]:
apoyo1 = Info_sheet.loc[(Info_sheet["Hospital al que llega"] == "Hospital Del Salvador") & (Info_sheet["GRD"] == "GRD9")&(Info_sheet["Día de llegada"] >= 420) ]
apoyo1 = apoyo1[['Número de llegada','Día de llegada']].groupby('Día de llegada').count()
apoyo1 = apoyo1.reset_index()
media_movil1 = np.round(apoyo1["Número de llegada"].mean(),)
print(f"Estimación pacientes que llegarán día 425 al Hospital Del Salvador es: {media_movil1}")

Estimación pacientes que llegarán día 425 al Hospital Del Salvador es: 3.0



Pregunta 2

¿Cuál de las siguientes alternativas corresponde a la estimación de la cantidad de pacientes que llegarán el día 425 al Hospital Salvador utilizando un método de media móvil sobre los últimos 5 días (días 420 a 424) redondeado al entero superior?  



In [ ]:
apoyo2 = Info_sheet[['Hospital al que llega','GRD', 'Día de llegada']]

In [ ]:
hosp_salvador = apoyo2.loc[apoyo2['Hospital al que llega']=='Hospital Del Salvador'].groupby("Día de llegada").count()


In [ ]:
media_movil2 = hosp_salvador.tail(5)
np.round(media_movil2.mean()[0],0)

12.0

Pregunta 3
¿Cuál de las siguientes alternativas corresponde a la estimación de la cantidad de pacientes que llegarán el día 425 a la red utilizando un método de media móvil sobre los últimos 5 días (días 420 a 424) redondeado al entero superior?   

In [ ]:
apoyo3 = Info_sheet[['Hospital al que llega','GRD', 'Día de llegada']]
apoyo3

Hospital al que llega    GRD  \
0           Instituto Traumatológico Dr. Teodoro Gebauer   GRD3   
1                    Hospital Clínico San Borja-Arriarán   GRD7   
2                             Hospital Dr. Luis Tisné B.   GRD7   
3                  Hospital Dr. Exequiel González Cortés  GRD10   
4                           Hospital Barros Luco Trudeau   GRD6   
...                                                  ...    ...   
65529                Hospital Clínico San Borja-Arriarán   GRD2   
65530              Hospital Dr. Exequiel González Cortés   GRD9   
65531                              Hospital Del Salvador  GRD10   
65532  Hospital de Enfermedades Infecciosas Dr. Lucio...   GRD3   
65533  Hospital de Urgencia Asistencia Pública Dr. Al...   GRD7   

       Día de llegada  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  
...               ...  
65529             424  
65530             424  
65531             424  
65532             424  
65533             424  

[65534 rows x 3 columns]

In [ ]:
hosp_generico = apoyo3.groupby("Día de llegada").count()
media_movil3= hosp_generico.tail(5)

In [ ]:
np.round(media_movil3.mean()[0],0)


149.0

Pregunta 4
¿Cuál de las siguientes alternativas corresponde a la estimación de la cantidad de pacientes con GRD9 que llegarán el día 425 al Hospital Salvador utilizando una regresión lineal simple sobre los últimos 5 días (días 420 a 424) redondeado al entero superior?  

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
apoyo4 = Info_sheet.loc[(Info_sheet["Hospital al que llega"] == "Hospital Del Salvador") & (Info_sheet["GRD"] == "GRD9")]
hosp_gr9 = apoyo4.groupby('Día de llegada').count()
hosp_gr9.tail(5)

Número de llegada  Hospital al que llega  GRD  Día de salida  \
Día de llegada                                                                 
417                             2                      2    2              2   
418                             1                      1    1              1   
420                             3                      3    3              3   
421                             2                      2    2              2   
422                             4                      4    4              4   

                Estadia  
Día de llegada           
417                   2  
418                   1  
420                   3  
421                   2  
422                   4

In [ ]:

# Filtrar los datos para el Hospital Del Salvador y GRD9
apoyo4 = Info_sheet.loc[(Info_sheet["Hospital al que llega"] == "Hospital Del Salvador") & (Info_sheet["GRD"] == "GRD9")]

# Agrupar por día de llegada y contar los pacientes
hosp_gr9 = apoyo4.groupby('Día de llegada').size().reset_index(name='Pacientes')

# Seleccionar los días de interés (420 a 424)
dias_interes = hosp_gr9[(hosp_gr9['Día de llegada'] >= 420) & (hosp_gr9['Día de llegada'] <= 424)]
dias_interes


Día de llegada  Pacientes
291             420          3
292             421          2
293             422          4

In [ ]:
# Filtrar los datos para el Hospital Del Salvador y GRD9
apoyo4 = Info_sheet.loc[(Info_sheet["Hospital al que llega"] == "Hospital Del Salvador") & (Info_sheet["GRD"] == "GRD9")]

# Agrupar por día de llegada y contar los pacientes
hosp_gr9 = apoyo4.groupby('Día de llegada').size().reset_index(name='Pacientes')

# Seleccionar los días de interés (420 a 424)
dias_interes = hosp_gr9[(hosp_gr9['Día de llegada'] >= 420) & (hosp_gr9['Día de llegada'] <= 424)]

# Verificar los datos seleccionados
print("Datos de los días de interés (420 a 424):")
print(dias_interes)

# Preparar los datos para la regresión
X = dias_interes[['Día de llegada']]
y = dias_interes[['Pacientes']]

regressor = LinearRegression().fit(X, y)
print(f"Pendiente: {regressor.coef_[0][0]}, Intercepto: {regressor.intercept_[0]}")

prox_llegada = 424*regressor.coef_[0][0]+regressor.intercept_[0]
print(f"Llegadas estimadas para el día 424: {np.round(prox_llegada,0)}")

Datos de los días de interés (420 a 424):
     Día de llegada  Pacientes
291             420          3
292             421          2
293             422          4
Pendiente: 0.4999999999999999, Intercepto: -207.49999999999994
Llegadas estimadas para el día 424: 4.0


In [ ]:
# Filtrar los datos para el Hospital Del Salvador y GRD9
apoyo4 = Info_sheet.loc[(Info_sheet["Hospital al que llega"] == "Hospital Del Salvador") & (Info_sheet["GRD"] == "GRD9")]

# Agrupar por día de llegada y contar los pacientes
hosp_gr9 = apoyo4.groupby('Día de llegada').size().reset_index(name='Pacientes')

# Seleccionar los días de interés (420 a 424)
dias_interes = hosp_gr9[(hosp_gr9['Día de llegada'] >= 420) & (hosp_gr9['Día de llegada'] <= 424)]

# Verificar los datos seleccionados
print("Datos de los días de interés (420 a 424):")
print(dias_interes)

# Preparar los datos para la regresión
X = dias_interes['Día de llegada'].values.reshape(-1, 1)
y = dias_interes['Pacientes'].values

# Ajustar el modelo de regresión lineal
model = LinearRegression()
model.fit(X, y)

# Predecir para el día 425
prediccion_dia_425 = model.predict([[425]])

# Redondear al entero superior
estimacion_dia_425 = np.ceil(prediccion_dia_425[0])

print(f"La estimación de la cantidad de pacientes con GRD9 que llegarán el día 425 al Hospital Del Salvador es: {estimacion_dia_425}")

Datos de los días de interés (420 a 424):
     Día de llegada  Pacientes
291             420          3
292             421          2
293             422          4
La estimación de la cantidad de pacientes con GRD9 que llegarán el día 425 al Hospital Del Salvador es: 5.0


In [ ]:
# Filtrar los datos para el Hospital Del Salvador y GRD9
apoyo5 = Info_sheet.loc[(Info_sheet["Hospital al que llega"] == "Hospital Del Salvador")]

# Agrupar por día de llegada y contar los pacientes
hosp_salv = apoyo5.groupby('Día de llegada').size().reset_index(name='Pacientes')

# Seleccionar los días de interés (420 a 424)
dias_interes = hosp_salv[(hosp_salv['Día de llegada'] >= 420) & (hosp_salv['Día de llegada'] <= 424)]

# Verificar los datos seleccionados
print("Datos de los días de interés (420 a 424):")
print(dias_interes)

# Preparar los datos para la regresión
X = dias_interes['Día de llegada'].values.reshape(-1, 1)
y = dias_interes['Pacientes'].values

# Ajustar el modelo de regresión lineal
model = LinearRegression()
model.fit(X, y)

# Predecir para el día 425
prediccion_dia_425 = model.predict([[425]])

# Redondear al entero superior
estimacion_dia_425 = np.ceil(prediccion_dia_425[0])

print(f"La estimación de la cantidad de pacientes con GRD que llegarán el día 425 al Hospital Del Salvador es: {estimacion_dia_425}")

Datos de los días de interés (420 a 424):
     Día de llegada  Pacientes
419             420         14
420             421         12
421             422         18
422             423          9
423             424          6
La estimación de la cantidad de pacientes con GRD que llegarán el día 425 al Hospital Del Salvador es: 7.0


In [ ]:
hosp_generico = Info_sheet.groupby('Día de llegada').size().reset_index(name='Pacientes')

# Seleccionar los días de interés (420 a 424)
dias_interes = hosp_generico[(hosp_generico['Día de llegada'] >= 420) & (hosp_generico['Día de llegada'] <= 424)]

# Verificar los datos seleccionados
print("Datos de los días de interés (420 a 424):")
print(dias_interes)

# Preparar los datos para la regresión
X = dias_interes['Día de llegada'].values.reshape(-1, 1)
y = dias_interes['Pacientes'].values

# Ajustar el modelo de regresión lineal
model = LinearRegression()
model.fit(X, y)

# Predecir para el día 425
prediccion_dia_425 = model.predict([[425]])

# Redondear al entero superior
estimacion_dia_425 = np.ceil(prediccion_dia_425[0])

print(f"La estimación de la cantidad de pacientes que llegarán a la red el día 425 es: {estimacion_dia_425}")

Datos de los días de interés (420 a 424):
     Día de llegada  Pacientes
419             420        183
420             421        159
421             422        160
422             423        159
423             424         82
La estimación de la cantidad de pacientes que llegarán a la red el día 425 es: 88.0


Pregunta 7
¿Cuál de las siguientes alternativas corresponde al valor del coeficiente R2 (R cuadrado) de una estimación sobre la cantidad de pacientes que llegarán a la red el día 425 utilizando una regresión lineal simple sobre los últimos 5 días (días 420 a 424)?  

In [ ]:
# Preparar los datos para la regresión
X = dias_interes['Día de llegada'].values.reshape(-1, 1)
y = dias_interes['Pacientes'].values

# Ajustar el modelo de regresión lineal
model = LinearRegression()
model.fit(X, y)

# Calcular el coeficiente R^2
r2_score = model.score(X, y)

print(f"El valor del coeficiente R^2 de la regresión lineal es: {r2_score}")

El valor del coeficiente R^2 de la regresión lineal es: 0.6840340642392606


Pregunta 8
Usted realizó una estimación sobre el total de pacientes que llegarán a la red los días 420 a 424, siendo esta predicción: 156, 123, 178, 200 y 155, para los días 420 a 424 respectivamente. ¿Cuál de las siguientes alternativas corresponde al error total de esta estimación?  


In [ ]:
# Valores reales de pacientes que llegaron los días 420 a 424 (debes proporcionar estos valores)
valores_reales = [183, 159, 160, 162, 82]  # Reemplaza con los valores reales

# Predicciones dadas
predicciones = [156, 123, 178, 200, 155]

# Calcular el error absoluto total
error_absoluto_total = sum(abs(real - pred) for real, pred in zip(valores_reales, predicciones))

print(f"Error absoluto total: {error_absoluto_total}")



Error absoluto total: 192
